# image ghcr.io/<user>/<name> adresinde yayınlanacak
name: xtechnology_ublue
# açıklama görselin meta verilerine dahil edilecek
description: uBlue görüntüleri kullanarak XTechnology tarafından kişiselleştirilmiş işletim sistemi
# (FROM) üzerine oluşturulacak temel görüntü ve kullanılacak sürüm etiketi
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # En kısa sürede yeni güncellemeler istiyorsanız en son sürüm de desteklenir
# modül konfigürasyonu, sırayla yürütülür
# aynı modülün birden fazla örneğini ekleyebilirsiniz
modules:
  - type: files
    files:
      - usr: /usr #statik yapılandırmaları kopyala
        #
        # config/files/usr dosyasını görüntünüzün /usr dosyasına kopyalar
        #
        # önyüklenen sistemde /etc/dizininde olmasını istediğiniz yapılandırma
        # /usr/etc/dizinine eklenmelidir çünkü bu uygun "dağıtım"dır
        # ostree'deki config dizini. Dosyalar modülünün README dosyasında daha fazlasını okuyun
  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode
    install:
      - nano
      - fish
      - langpacks-tr
      - acpid
      - acpi
      - gnome-tweaks
      - inxi
      - python3-pip
    remove:
      - firefox # varsayılan firefox, düzpak lehine kaldırıldı
      - firefox-langpacks # Bağımlılık sorunlarını önlemek için langpack'lerin de kaldırılması gerekiyor
  - type: akmods
    install:
      - nvidia
      - ublue-os-nvidia-addons
      - ublue-os-akmods-addons
  - type: bling # ublue-os/bling'den ne alınacağını yapılandırın
    install:
      - justfiles # "!include /usr/share/ublue-os/just/100-bling.just" ekleyin
      #custom.just dosyanızda (varsayılan olarak eklenir) veya yerel justfile dosyasında
      - nix-installer #belirli sistemler için kabuk kısayolları nix yükleyicisi
      - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      - container-tools # konteynerle ilgili araçları /usr/bin üzerine yükler: kind, kubectx, docker-compose ve kubens
      - laptop # TLP'yi yükler ve sisteminizi dizüstü bilgisayar kullanımı için yapılandırır
  - type: yafti # dahilse, yafti ve bağımlılıkları (pip & libadwaita)
    # yüklenecek ve kurulacak
    custom-flatpaks: # bu bölüm isteğe bağlıdır
      - Extension Manager: com.mattjakeman.ExtensionManager
      - Discord: com.discordapp.Discord
      - Telegram Desktop: org.telegram.desktop
      - Prompt: org.gnome.Prompt.Devel
      - FileZilla: org.filezillaproject.Filezilla
      - Microsoft Edge (dev): com.microsoft.EdgeDev
  - type: script
    scripts:
      # bu, imzalı görsellerin çalışması için uygun politika ve imzalama dosyalarını ayarlar
      - signing.sh
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode #"Nerd Font" son ekini eklemeyin.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
